org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
# We must keep at as some lib continue to `apply kotlin-android`
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
# We must keep at as some lib continue to use the old DSL
android.newDsl=false
