when:
    branch: main
    event: [push, pull_request, manual]

steps:
    - name: Init
      # Fork of https://github.com/MobileDevOps/flutter-sdk-image
      image: codeberg.org/s1m/flutter-sdk-image:latest
      commands:
        - git config --global --add safe.directory /home/mobiledevops/.flutter-sdk
        - ./dev.sh
        - cd ./unifiedpush_platform_interface
        - flutter pub get
        - cd ../unifiedpush
        - flutter pub get
        - cd ../unifiedpush_android
        - flutter pub get
        - cd ../example
        - flutter pub get
    - name: Build Android
      image: codeberg.org/s1m/flutter-sdk-image:latest
      commands:
        - cd example
        - flutter build apk
        - cd ..
        - mv ./example/build/app/outputs/flutter-apk/app-release.apk flutter-example.apk
    - name: Build Linux
      image: codeberg.org/s1m/flutter-sdk-image:latest
      commands:
        - cd example
        - flutter build linux
        - cd build/linux/x64/release/bundle
        - zip -r flutter-example-linux.zip .
        - cd ../../../../../..
        - mv ./example/build/linux/x64/release/bundle/flutter-example-linux.zip .
    - name: Upload
      image: codeberg.org/s1m/woodpecker-upload:latest
      settings:
          token:
              from_secret: codeberg_token
          file:
              - flutter-example.apk
          package: true
